### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by skizap** [MikronT/911Help#1]
Hello could you make an English option? This looks amazing but i cant understand it :(

**Comment by MikronT** [comment]
Thanks! This is just an HTML help for my 911 programs collection, though I was thinking about translation)

**Comment by MikronT** [comment]
I thinking to translate all repositories to English for better accessibility

**Comment by MikronT** [comment]
Thanks for idea)))

**Comment by MikronT** [comment]
All repositories translated to English
